import { iconType } from '../../types/iconType'

export const materialIconData: iconType[] = [
  {
    name: 'material',
    genre: 'action',
    icon: '3d_rotation',
    tag: ['ローテーション', '回転'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'accessibility',
    tag: ['人', 'ユニバーサル', 'アクセシビリティ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'accessible',
    tag: ['車椅子', '人', 'ユニバーサル', 'アクセシビリティ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'account_balance',
    tag: ['銀行'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'account_balance_wallet',
    tag: ['銀行', '財布'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'account_box',
    tag: ['アカウント'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'account_circle',
    tag: ['アカウント'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'add_shopping_cart',
    tag: ['ショッピングカート', '＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'alarm',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'alarm_add',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm', '追加', '＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'alarm_off',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'alarm_on',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'all_out',
    tag: ['アラーム', '時計'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'android',
    tag: ['アンドロイド', 'OS'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'announcement',
    tag: ['発表', '告知', 'アナウンス'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'aspect_ratio',
    tag: ['アスペクト比', '縦横比'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'assessment',
    tag: ['評価', '査定', 'アセスメント'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'assignment',
    tag: ['宿題', '課題', '仕事', '地位'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'assignment_ind',
    tag: ['宿題', '課題', '仕事', '地位', '人'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'assignment_late',
    tag: ['宿題', '課題', '仕事', '地位', '感嘆符'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'assignment_return',
    tag: ['宿題', '課題', '仕事', '地位', '左', 'リターン'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'assignment_returned',
    tag: ['宿題', '課題', '仕事', '地位', '下'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'assignment_turned_in',
    tag: ['宿題', '課題', '仕事', '地位', 'チェック', 'レ点'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'autorenew',
    tag: ['自動', '更新'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'backup',
    tag: ['バックアップ', '保存', 'クラウド'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'book',
    tag: ['本', '書籍', '名簿', 'ブック'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'bookmark',
    tag: ['しおり', '栞', 'ブックマーク'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'bookmark_border',
    tag: ['しおり', '栞', 'ブックマーク'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'bug_report',
    tag: ['バグ', 'レポート', '報告', 'リポート'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'build',
    tag: ['ビルド', 'スパナ', 'レンチ', '工具', 'wrench'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'cached',
    tag: ['キャッシュ', '更新'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'camera_enhance',
    tag: ['カメラ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'card_giftcard',
    tag: ['ギフトカード'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'card_membership',
    tag: ['メンバーシップ', 'カード'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'card_travel',
    tag: ['カード', '旅行'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'change_history',
    tag: ['変更履歴', '△'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'check_circle',
    tag: ['チェック', 'レ点'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'chrome_reader_mode',
    tag: ['読み込み'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'class',
    tag: ['クラス'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'code',
    tag: ['コード', 'タグ', '<>'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'compare_arrows',
    tag: ['矢印', '競合', '比較', '比べる'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'copyright',
    tag: ['著作権', 'コピーライト', '版権'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'credit_card',
    tag: ['クレジットカード'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'dashboard',
    tag: ['ダッシュボード', '統計'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'date_range',
    tag: ['時系列'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'delete',
    tag: ['削除', 'ゴミ箱', 'デリート', '消す'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'delete_forever',
    tag: ['削除', 'ゴミ箱', 'デリート', '消す'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'description',
    tag: ['記述', '描写', '説明書', '解説書'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'dns',
    tag: ['DNS'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'done',
    tag: ['終了', 'チェック', 'レ点'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'done_all',
    tag: ['終了', 'チェック', 'レ点'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'donut_large',
    tag: ['ドーナツグラフ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'donut_small',
    tag: ['ドーナツグラフ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'eject',
    tag: ['イジェクト', '排出', 'トレイ', '取り出す'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'euro_symbol',
    tag: ['ユーロ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'event',
    tag: ['イベント'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'event_seat',
    tag: ['イベント', 'シート', '座席', '観客席'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'exit_to_app',
    tag: ['終了', '退場'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'explore',
    tag: ['探査', '踏査', '探求', '探究', '調査'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'extension',
    tag: ['エクステンション', '拡張'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'face',
    tag: ['顔'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'favorite',
    tag: ['heart', 'ハート', '心', 'いいね', 'love', 'ラブ', 'ライク', 'like', '好き'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'favorite_border',
    tag: ['heart', 'ハート', '心', 'いいね', 'love', 'ラブ', 'ライク', 'like', '好き'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'feedback',
    tag: ['フィードバック', '意見', '反応'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'find_in_page',
    tag: ['探す', 'ページ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'find_replace',
    tag: ['探す', '置き換える'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'fingerprint',
    tag: ['フィンガープリント', '指紋'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'flight_land',
    tag: ['フライト', '着陸', ',飛行機'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'flight_takeoff',
    tag: ['フライト', '離陸', ',飛行機'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'flip_to_back',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'flip_to_front',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'g_translate',
    tag: ['グーグル翻訳'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'gavel',
    tag: ['小槌', '裁判', '競売', 'ハンマー'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'get_app',
    tag: ['ゲット', '入手', '取得'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'gif',
    tag: ['gif'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'grade',
    tag: ['スター', '星', 'グレード'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'group_work',
    tag: ['グループ', 'ワーク', 'グループワーク', '集団労働'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'help',
    tag: ['ヘルプ', 'はてな', 'ハテナ', '?', '？'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'help_outline',
    tag: ['ヘルプ', 'はてな', 'ハテナ', '?', '？'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'highlight_off',
    tag: ['ハイライト'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'history',
    tag: ['履歴', '歴史', '経歴', '来歴', '沿革'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'home',
    tag: ['ホーム', '家'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'hourglass_empty',
    tag: ['砂時計', '水時計'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'hourglass_full',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'http',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'https',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'important_devices',
    tag: ['デバイス', 'デスクトップ', 'スマートフォン'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'info',
    tag: ['情報'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'info_outline',
    tag: ['情報'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'input',
    tag: ['入力'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'invert_colors',
    tag: ['色', '反転'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'label',
    tag: ['ラベル', '付箋', '荷札'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'label_outline',
    tag: ['ラベル', '付箋', '荷札'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'language',
    tag: ['言語', '世界', '地球', 'lang'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'launch',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'lightbulb_outline',
    tag: ['白熱電球', 'ランプ', '蛍光'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'line_style',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'line_weight',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'list',
    tag: ['リスト', '表', '目録', '名簿'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'lock',
    tag: ['鍵', '施錠', 'ロック'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'lock_open',
    tag: ['鍵', '施錠', 'オープン', '開場'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'lock_outline',
    tag: ['鍵', '施錠', 'ロック'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'loyalty',
    tag: ['忠実', '忠誠'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'markunread_mailbox',
    tag: ['メール'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'motorcycle',
    tag: ['オートバイク', '単車', 'バイク'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'note_add',
    tag: ['ノート', 'メモ', 'memo', '追加', 'メモ', '＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'offline_pin',
    tag: ['ピン'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'opacity',
    tag: ['不透明度'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'open_in_browser',
    tag: ['ブラウザ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'open_in_new',
    tag: ['新規'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'open_with',
    tag: ['拡張'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'pageview',
    tag: ['pv', '閲覧'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'pan_tool',
    tag: ['手', 'ハンド'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'payment',
    tag: ['支払い', 'カード'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_camera_mic',
    tag: ['カメラ', 'マイク'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_contact_calendar',
    tag: ['人', 'カレンダー'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_data_setting',
    tag: ['データ', '歯車', '設定', 'env'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_device_information',
    tag: ['注意', 'デバイス', '重要'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_identity',
    tag: ['人'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_media',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_phone_msg',
    tag: ['メッセージ', '電話', 'sms', 'message'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'perm_scan_wifi',
    tag: ['注意', '重要', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'pets',
    tag: ['ペット', '肉球', '足跡'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'picture_in_picture',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'picture_in_picture_alt',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'play_for_work',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'polymer',
    tag: ['ポリマー'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'power_settings_new',
    tag: ['電源', 'シャットダウン'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'pregnant_woman',
    tag: ['妊婦', '妊娠'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'print',
    tag: ['プリンター', 'ファックス', 'プリント'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'query_builder',
    tag: ['時計', 'タイマー'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'question_answer',
    tag: ['qa', 'qanda', 'q&a'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'receipt',
    tag: ['レシート', '受領証', '領収書'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'record_voice_over',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'redeem',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'remove_shopping_cart',
    tag: ['ショッピングカート'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'reorder',
    tag: ['再秩序', '再注文', '再整理'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'report_problem',
    tag: ['レポート', 'リポート', '重要', '感嘆符', '報告'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'restore',
    tag: ['リストア', '更新', '修復', '修理'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'restore_page',
    tag: ['リストア', '更新', '修復', '修理', 'ページ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'room',
    tag: ['部屋', '場所', '現在位置', 'ピン', '地図'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'rounded_corner',
    tag: ['角', '丸みを帯びた'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'rowing',
    tag: ['ボート', '漕ぐ', 'オール'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'schedule',
    tag: ['スケジュール', '時計', '予定'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'search',
    tag: ['検索', 'サーチ', '虫眼鏡', '探す'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings',
    tag: ['設定', '歯車', 'セッティング'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_applications',
    tag: ['設定', '歯車'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_backup_restore',
    tag: ['バックアップ', 'リストア'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_bluetooth',
    tag: ['青歯', 'ブルートゥース'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_brightness',
    tag: ['明るさ', 'ライトモード'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_cell',
    tag: ['スマートフォン'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_ethernet',
    tag: ['イーサネット'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_input_antenna',
    tag: ['アンテナ'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_input_component',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_input_composite',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_input_hdmi',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_input_svideo',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_overscan',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_phone',
    tag: ['電話'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_power',
    tag: ['電源'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_remote',
    tag: ['リモート', '電波'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'settings_voice',
    tag: ['ボイス', 'マイク'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'shop',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'shop_two',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'shopping_basket',
    tag: ['ショッピング', '買い物かご', '買い物籠'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'shopping_cart',
    tag: ['ショッピングカート'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'speaker_notes',
    tag: ['ノート', 'メモ', 'memo'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'speaker_notes_off',
    tag: ['ノート', 'メモ', 'memo'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'spellcheck',
    tag: ['スペルチェック'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'star_rate',
    tag: ['星', 'スター'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'stars',
    tag: ['星', 'スター'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'store',
    tag: ['お店', '商店', 'デパート'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'subject',
    tag: ['タイトル', '主題', '題目', '議題', 'テーマ', '科目', '話題'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'supervisor_account',
    tag: ['管理者', 'アカウント'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'swap_horiz',
    tag: ['矢印', '左右', '入れ替え'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'swap_vert',
    tag: ['矢印', '上下', '入れ替え'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'swap_vertical_circle',
    tag: ['矢印', '上下', '入れ替え'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'system_update_alt',
    tag: ['システム', 'アップデート'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'tab',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'tab_unselected',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'theaters',
    tag: ['シアター', 'フィルム', '映画', '映像'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'thumb_down',
    tag: ['bad', '悪', '否定'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'thumb_up',
    tag: ['good', '良', '肯定', 'いいね'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'thumbs_up_down',
    tag: ['good', '良', '肯定', 'bad', '悪', '否定'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'timeline',
    tag: ['タイムライン', 'スケジュール', '年表', '時系列', '史'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'toc',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'today',
    tag: ['今日'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'toll',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'touch_app',
    tag: ['タッチ', '指', '押す', 'ボタン'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'track_changes',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'translate',
    tag: ['翻訳', '言語', 'lang', 'language'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'trending_down',
    tag: ['統計', 'トレンド', '下がり'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'trending_flat',
    tag: ['統計', 'トレンド', '一定'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'trending_up',
    tag: ['統計', 'トレンド', '上がり'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'turned_in',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'turned_in_not',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'update',
    tag: ['アップデート', '更新'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'verified_user',
    tag: ['認証', '確認', '検証', '認定'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_agenda',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_array',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_carousel',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_column',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_day',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_headline',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_list',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_module',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_quilt',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_stream',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'view_week',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'visibility',
    tag: ['可視性', '視界'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'visibility_off',
    tag: ['可視性', '視界'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'watch_later',
    tag: ['時計'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'work',
    tag: ['仕事', 'かばん', 'カバン', '鞄', 'バック', 'bag', 'ビジネス'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'youtube_searched_for',
    tag: [],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'zoom_in',
    tag: ['ズーム', '拡大'],
  },
  {
    name: 'material',
    genre: 'action',
    icon: 'zoom_out',
    tag: ['ズーム', '縮小'],
  },
  {
    name: 'material',
    genre: 'alert',
    icon: 'add_alert',
    tag: ['アラート', 'ベル', '通知', '＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'alert',
    icon: 'error',
    tag: ['エラー', '重量'],
  },
  {
    name: 'material',
    genre: 'alert',
    icon: 'error_outline',
    tag: ['エラー', '重量'],
  },
  {
    name: 'material',
    genre: 'alert',
    icon: 'warning',
    tag: ['エラー', '重量', 'ワーニング', '注意', '警戒', '危険'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'add_to_queue',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'airplay',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'album',
    tag: ['アルバム', 'CD', '円盤', 'DVD', 'BL', '音楽'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'art_track',
    tag: ['音楽', 'トラック'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'av_timer',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'branding_watermark',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'call_to_action',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'closed_caption',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'equalizer',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'explicit',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'fast_forward',
    tag: ['早送り', '進む', 'go', 'next', '進む'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'fast_rewind',
    tag: ['巻き戻し', '戻る', 'prev', 'previous', 'back', '戻る'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'featured_play_list',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'featured_video',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'fiber_dvr',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'fiber_manual_record',
    tag: ['録音', '録画', '丸', '◯', 'マル', 'circle'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'fiber_new',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'fiber_pin',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'fiber_smart_record',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'forward_10',
    tag: ['早送り', '進む', 'go', 'next', '進む'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'forward_30',
    tag: ['早送り', '進む', 'go', 'next', '進む'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'forward_5',
    tag: ['早送り', '進む', 'go', 'next', '進む'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'games',
    tag: ['十字キー'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'hd',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'hearing',
    tag: ['耳', '聞く', '聴く'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'high_quality',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'library_add',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'library_books',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'library_music',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'loop',
    tag: ['ループ', '繰り返し', 'リサイクル', 'リピート', 'repeat'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'mic',
    tag: ['マイク'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'movie',
    tag: ['映画'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'new_releases',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'not_interested',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'note',
    tag: ['ノート', 'メモ', 'memo'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'pause',
    tag: ['ポーズ', '停止', '中断', 'stop', 'ストップ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'pause_circle_filled',
    tag: ['ポーズ', '停止', '中断', 'stop', 'ストップ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'pause_circle_outline',
    tag: ['ポーズ', '停止', '中断', 'stop', 'ストップ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'play_arrow',
    tag: ['再生', '再開', 'スタート', 'start'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'play_circle_filled',
    tag: ['再生', '再開', 'スタート', 'start'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'play_circle_filled_white',
    tag: ['再生', '再開', 'スタート', 'start'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'play_circle_outline',
    tag: ['再生', '再開', 'スタート', 'start'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'playlist_add',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'playlist_add_check',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'playlist_play',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'queue',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'queue_music',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'queue_play_next',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'radio',
    tag: ['ラジオ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'recent_actors',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'remove_from_queue',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'repeat',
    tag: ['ループ', '繰り返し', 'リサイクル', 'リピート', 'repeat'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'repeat_one',
    tag: ['ループ', '繰り返し', 'リサイクル', 'リピート', 'repeat'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'replay',
    tag: ['ループ', '繰り返し', 'リサイクル', 'リピート', 'repeat'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'replay_10',
    tag: ['ループ', '繰り返し', 'リサイクル', 'リピート', 'repeat'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'replay_30',
    tag: ['ループ', '繰り返し', 'リサイクル', 'リピート', 'repeat'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'replay_5',
    tag: ['ループ', '繰り返し', 'リサイクル', 'リピート', 'repeat'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'shuffle',
    tag: ['シャッフル'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'skip_next',
    tag: ['次'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'skip_previous',
    tag: ['戻る'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'slow_motion_video',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'snooze',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'sort_by_alpha',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'stop',
    tag: ['ポーズ', '停止', '中断', 'stop', 'ストップ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'subscriptions',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'subtitles',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'surround_sound',
    tag: [],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'video_call',
    tag: ['ビデオ', 'カメラ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'video_label',
    tag: ['ビデオ', 'カメラ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'video_library',
    tag: ['ビデオ', 'カメラ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'videocam',
    tag: ['ビデオ', 'カメラ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'videocam_off',
    tag: ['ビデオ', 'カメラ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'volume_down',
    tag: ['ボリューム', '音'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'volume_mute',
    tag: ['ボリューム', '音'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'volume_off',
    tag: ['ボリューム', '音'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'volume_up',
    tag: ['ボリューム', '音'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'web',
    tag: ['ウェブ'],
  },
  {
    name: 'material',
    genre: 'av',
    icon: 'web_asset',
    tag: ['ウェブ'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'business',
    tag: ['ビジネス', '仕事'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call_end',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call_made',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call_merge',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call_missed',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call_missed_outgoing',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call_received',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'call_split',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'chat',
    tag: ['チャット', 'メッセージ', 'message'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'chat_bubble',
    tag: ['チャット', 'メッセージ', 'message'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'chat_bubble_outline',
    tag: ['チャット', 'メッセージ', 'コメント', 'message'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'clear_all',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'comment',
    tag: ['チャット', 'メッセージ', 'コメント', 'message'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'contact_mail',
    tag: ['コンタクト', 'メール'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'contact_phone',
    tag: ['コンタクト', 'フォン', '携帯'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'contacts',
    tag: ['コンタクト'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'dialer_sip',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'dialpad',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'email',
    tag: ['メール'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'forum',
    tag: ['フォーラム', 'コミュニティ'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'import_contacts',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'import_export',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'invert_colors_off',
    tag: ['色', '反転'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'live_help',
    tag: ['ヘルプ', 'はてな', 'ハテナ', '?', '？'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'location_off',
    tag: ['場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'location_on',
    tag: ['場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'mail_outline',
    tag: ['メール'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'message',
    tag: ['メッセージ', 'sms', 'チャット', 'コメント'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'no_sim',
    tag: ['シム'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'phone',
    tag: ['携帯', '電話', '受話器', 'call'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'phonelink_erase',
    tag: ['スマートフォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'phonelink_lock',
    tag: ['スマートフォン', 'ロック'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'phonelink_ring',
    tag: ['スマートフォン', '電波'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'phonelink_setup',
    tag: ['スマートフォン', '設定'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'portable_wifi_off',
    tag: ['ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'present_to_all',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'ring_volume',
    tag: ['携帯', '電話', '受話器', 'call'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'rss_feed',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'screen_share',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'speaker_phone',
    tag: ['volume', '音声', 'スマートフォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'stay_current_landscape',
    tag: ['スマートフォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'stay_current_portrait',
    tag: ['スマートフォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'stay_primary_landscape',
    tag: ['スマートフォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'stay_primary_portrait',
    tag: ['スマートフォン'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'stop_screen_share',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'swap_calls',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'textsms',
    tag: ['message', 'メッセージ'],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'voicemail',
    tag: [],
  },
  {
    name: 'material',
    genre: 'communication',
    icon: 'vpn_key',
    tag: ['キー', '鍵'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'add',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'add_box',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'add_circle',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'add_circle_outline',
    tag: ['＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'archive',
    tag: ['アーカイブ'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'backspace',
    tag: ['戻る', '×', 'バツ', 'back', 'バック'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'block',
    tag: ['ブロック', '凍結', '禁止', '不可'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'clear',
    tag: ['cancel', 'キャンセル', '戻る', '×', 'バツ', '☓', 'back', 'バック', 'クリア', 'clear', 'クローズ', 'close'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'content_copy',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'content_cut',
    tag: ['カット', 'ハサミ', 'はさみ', '鋏'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'content_paste',
    tag: ['ボード'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'create',
    tag: ['ペン', 'edit', '編集'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'delete_sweep',
    tag: ['削除', 'ゴミ箱', 'デリート', '消す'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'drafts',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'filter_list',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'flag',
    tag: ['旗', 'はた'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'font_download',
    tag: ['フォント'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'forward',
    tag: ['矢印', 'prev', 'previous', 'back', '戻る'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'gesture',
    tag: ['ジェスチャー'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'inbox',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'link',
    tag: ['リンク', '紐付け'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'low_priority',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'mail',
    tag: ['メール'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'markunread',
    tag: ['メール'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'move_to_inbox',
    tag: ['メール'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'next_week',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'redo',
    tag: ['矢印', '戻る', '巻き戻し'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'remove',
    tag: ['除'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'remove_circle',
    tag: ['除'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'remove_circle_outline',
    tag: ['除'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'reply',
    tag: ['リプライ', '返信', '応答'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'reply_all',
    tag: ['リプライ', '返信', '応答'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'report',
    tag: ['レポート', 'リポート', '重要', '感嘆符', '報告'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'save',
    tag: ['セーブ', '保存', 'フロッピーディスク'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'select_all',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'send',
    tag: ['送信', '送る'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'sort',
    tag: ['並び替え'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'text_format',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'unarchive',
    tag: [],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'undo',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'content',
    icon: 'weekend',
    tag: ['ソファー', 'くつろぐ', '癒し', '家具'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'access_alarm',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'access_alarms',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'access_time',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'add_alarm',
    tag: ['＋', '+', 'add', '追加', 'アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'airplanemode_active',
    tag: ['飛行機', '機内モード'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'airplanemode_inactive',
    tag: ['飛行機', '機内モード'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'battery_alert',
    tag: ['バッテリー', '充電', '電池'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'battery_charging_full',
    tag: ['バッテリー', '充電', '電池'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'battery_full',
    tag: ['バッテリー', '充電', '電池'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'battery_std',
    tag: ['バッテリー', '充電', '電池'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'battery_unknown',
    tag: ['バッテリー', '充電', '電池'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'bluetooth',
    tag: ['ブルートゥース'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'bluetooth_connected',
    tag: ['ブルートゥース'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'bluetooth_disabled',
    tag: ['ブルートゥース'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'bluetooth_searching',
    tag: ['ブルートゥース'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'brightness_auto',
    tag: ['ブルートゥース'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'brightness_high',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'brightness_low',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'brightness_medium',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'data_usage',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'developer_mode',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'devices',
    tag: ['デスクトップ', 'スマートフォン'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'dvr',
    tag: ['デスクトップ'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'gps_fixed',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'gps_not_fixed',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'gps_off',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'location_disabled',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'location_searching',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'network_cell',
    tag: ['ネット', '回線', '電波', 'ネットワーク'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'network_wifi',
    tag: ['ネット', '回線', '電波', 'ネットワーク'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'nfc',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'screen_lock_landscape',
    tag: ['スマートフォン', 'ロック', '鍵', '施錠'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'screen_lock_portrait',
    tag: ['スマートフォン', 'ロック', '鍵', '施錠'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'screen_lock_rotation',
    tag: ['ローテーション', '回転'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'screen_rotation',
    tag: ['ローテーション', '回転'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'sd_storage',
    tag: ['SDカード', 'sd', 'メモリー', 'カード'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'settings_system_daydream',
    tag: ['クラウド'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_cellular_4_bar',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_cellular_connected_no_internet_4_bar',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_cellular_no_sim',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_cellular_null',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_cellular_off',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_wifi_4_bar',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_wifi_4_bar_lock',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'signal_wifi_off',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'storage',
    tag: ['ストレージ', 'サーバー', 'DB'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'usb',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'wallpaper',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'widgets',
    tag: [],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'wifi_lock',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'device',
    icon: 'wifi_tethering',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'attach_file',
    tag: ['ファイル', 'クリップ', 'clip'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'attach_money',
    tag: ['dollar', 'ダラー', '金', 'ドル', '弗', '$', '＄'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_all',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_bottom',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_clear',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_color',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_horizontal',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_inner',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_left',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_outer',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_right',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_style',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_top',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'border_vertical',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'bubble_chart',
    tag: ['チャート', '統計'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'drag_handle',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_align_center',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_align_justify',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_align_left',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_align_right',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_bold',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_clear',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_color_fill',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_color_reset',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_color_text',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_indent_decrease',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_indent_increase',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_italic',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_line_spacing',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_list_bulleted',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_list_numbered',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_paint',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_quote',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_shapes',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_size',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_strikethrough',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_textdirection_l_to_r',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_textdirection_r_to_l',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'format_underlined',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'functions',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'highlight',
    tag: ['ハイライト'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'insert_chart',
    tag: ['チャート', '統計'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'insert_comment',
    tag: ['チャット', 'メッセージ', 'コメント', 'レポート', 'リポート', '重要', '感嘆符', '報告', 'message'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'insert_drive_file',
    tag: ['ファイル', 'doc', 'ドキュメント'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'insert_emoticon',
    tag: ['絵文字'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'insert_invitation',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'insert_link',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'insert_photo',
    tag: ['写真', '絵', 'picture'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'linear_scale',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'merge_type',
    tag: ['矢印'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'mode_comment',
    tag: ['チャット', 'メッセージ', 'コメント', 'message'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'mode_edit',
    tag: ['ペン', 'edit', 'edit', '編集'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'monetization_on',
    tag: ['ドル', 'dollar', 'ダラー', '金'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'money_off',
    tag: ['ドル', 'dollar', 'ダラー', '金'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'multiline_chart',
    tag: ['チャート', '統計'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'pie_chart',
    tag: ['チャート', '統計'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'pie_chart_outlined',
    tag: ['チャート', '統計'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'publish',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'short_text',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'show_chart',
    tag: ['チャート', '統計'],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'space_bar',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'strikethrough_s',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'text_fields',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'title',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'vertical_align_bottom',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'vertical_align_center',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'vertical_align_top',
    tag: [],
  },
  {
    name: 'material',
    genre: 'editor',
    icon: 'wrap_text',
    tag: [],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'attachment',
    tag: ['クリップ', 'file', 'clip', 'ファイル'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'cloud',
    tag: ['クラウド'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'cloud_circle',
    tag: ['クラウド'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'cloud_done',
    tag: ['クラウド', '終了', 'レ点'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'cloud_download',
    tag: ['クラウド', '矢印', 'ダウンロード'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'cloud_off',
    tag: ['クラウド'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'cloud_queue',
    tag: ['クラウド'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'cloud_upload',
    tag: ['クラウド', '矢印', 'アップロード'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'create_new_folder',
    tag: ['フォルダー', '＋', '+', 'add', '追加'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'file_download',
    tag: ['矢印', 'ダウンロード'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'file_upload',
    tag: ['矢印', 'アップロード'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'folder',
    tag: ['フォルダー'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'folder_open',
    tag: ['フォルダー'],
  },
  {
    name: 'material',
    genre: 'file',
    icon: 'folder_shared',
    tag: ['フォルダー', '共有'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'cast',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'cast_connected',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'computer',
    tag: ['pc', 'コンピューター', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'desktop_mac',
    tag: ['pc', 'コンピューター', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'desktop_windows',
    tag: ['pc', 'コンピューター', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'developer_board',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'device_hub',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'devices_other',
    tag: ['デスクトップ', 'スマートフォン'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'dock',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'gamepad',
    tag: ['十字キー'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'headset',
    tag: ['ヘッドセット', 'ヘッドフォン', 'headphone'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'headset_mic',
    tag: ['ヘッドセット', 'ヘッドフォン', 'headphone'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard',
    tag: ['キーボード'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_arrow_down',
    tag: ['矢印'],
  }, //  これの記号
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_arrow_left',
    tag: ['<', '矢印', 'prev', 'previous', 'back', '戻る'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_arrow_right',
    tag: ['>', '矢印', 'go', 'next', '進む'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_arrow_up',
    tag: ['^', '矢印'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_backspace',
    tag: ['キーボード', 'prev', 'previous', 'back', '戻る'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_capslock',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_hide',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_return',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_tab',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'keyboard_voice',
    tag: ['マイク', 'mic'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'laptop',
    tag: ['ラップトップ', 'desktop', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'laptop_chromebook',
    tag: ['ラップトップ', 'desktop', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'laptop_mac',
    tag: ['ラップトップ', 'desktop', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'laptop_windows',
    tag: ['ラップトップ', 'desktop', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'memory',
    tag: ['メモリー'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'mouse',
    tag: ['マウス'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'phone_android',
    tag: ['スマートフォン', 'アンドロイド', 'スマートフォン', 'smartphone', 'モバイル', 'mobile'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'phone_iphone',
    tag: ['スマートフォン', 'アイフォン', 'スマートフォン', 'smartphone', 'モバイル', 'mobile'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'phonelink',
    tag: ['スマートフォン', 'デスクトップ', 'スマートフォン', 'smartphone', 'モバイル', 'mobile'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'phonelink_off',
    tag: ['スマートフォン', 'デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'power_input',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'router',
    tag: ['ルーター'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'scanner',
    tag: ['スキャナー'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'security',
    tag: ['セキュリティ', 'ウイルス'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'sim_card',
    tag: ['SIMカード'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'smartphone',
    tag: ['スマートフォン', 'smartphone', 'モバイル', 'mobile'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'speaker',
    tag: ['スピーカー'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'speaker_group',
    tag: ['スピーカー'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'tablet',
    tag: ['タブレット'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'tablet_android',
    tag: ['タブレット'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'tablet_mac',
    tag: ['タブレット'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'toys',
    tag: [],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'tv',
    tag: ['デスクトップ'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'videogame_asset',
    tag: ['ビデオ', 'ゲーム'],
  },
  {
    name: 'material',
    genre: 'hardware',
    icon: 'watch',
    tag: ['スマートウォッチ', 'smartwatch'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'add_a_photo',
    tag: ['＋', '+', 'add', '追加', 'フォト', 'カメラ', 'camera'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'add_to_photos',
    tag: ['＋', '+', 'add', '追加', 'フォト', 'カメラ', 'camera'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'adjust',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'assistant',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'assistant_photo',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'audiotrack',
    tag: ['音符', 'music', 'ミュージック', 'sound', 'サウンド', '音楽'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'blur_circular',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'blur_linear',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'blur_off',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'blur_on',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brightness_1',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brightness_2',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brightness_3',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brightness_4',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brightness_5',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brightness_6',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brightness_7',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'broken_image',
    tag: ['明度', '輝度', '明るさ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'brush',
    tag: ['筆'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'burst_mode',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'camera',
    tag: ['カメラ', 'photo', 'フォト'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'camera_alt',
    tag: ['カメラ', 'photo', 'フォト'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'camera_front',
    tag: ['カメラ', 'photo', 'フォト'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'camera_rear',
    tag: ['カメラ', 'photo', 'フォト'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'camera_roll',
    tag: ['カメラ', 'photo', 'フォト'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'center_focus_strong',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'center_focus_weak',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'collections',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'collections_bookmark',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'color_lens',
    tag: ['色'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'colorize',
    tag: ['色', '抽出'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'compare',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'control_point',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'control_point_duplicate',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_16_9',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_3_2',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_5_4',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_7_5',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_din',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_free',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_landscape',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_original',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_portrait',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_rotate',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'crop_square',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'dehaze',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'details',
    tag: ['△', '三角'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'edit',
    tag: ['ペン', 'edit', 'edit', '編集'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'exposure',
    tag: ['+', '-', 'プラス', 'マイナス'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'exposure_neg_1',
    tag: ['マイナス', '−', '1'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'exposure_neg_2',
    tag: ['マイナス', '−', '2'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'exposure_plus_1',
    tag: ['プラス', '＋', '1'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'exposure_plus_2',
    tag: ['プラス', '＋', '2'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'exposure_zero',
    tag: ['0'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_1',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_2',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_3',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_4',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_5',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_6',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_7',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_8',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_9',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_9_plus',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_b_and_w',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_center_focus',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_drama',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_frames',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_hdr',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_none',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_tilt_shift',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'filter_vintage',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'flare',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'flash_auto',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'flash_off',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'flash_on',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'flip',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'gradient',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'grain',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'grid_off',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'grid_on',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'hdr_off',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'hdr_on',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'hdr_strong',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'hdr_weak',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'healing',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'image',
    tag: ['イメージ', '画像', 'picture', '絵'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'image_aspect_ratio',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'iso',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'landscape',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'leak_add',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'leak_remove',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'lens',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'linked_camera',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'looks',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'looks_3',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'looks_4',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'looks_5',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'looks_6',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'looks_one',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'looks_two',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'loupe',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'monochrome_photos',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'movie_creation',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'movie_filter',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'nature',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'nature_people',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'navigate_before',
    tag: ['<', '矢印', 'prev', 'previous', 'back', '戻る'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'navigate_next',
    tag: ['>', '矢印', 'go', 'next', '進む'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'palette',
    tag: ['パレット', '色', 'color'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'panorama',
    tag: ['イメージ', '画像', 'picture', '絵'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'panorama_fish_eye',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'panorama_horizontal',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'panorama_vertical',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'panorama_wide_angle',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo',
    tag: ['イメージ', '画像', 'picture', '絵'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo_album',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo_camera',
    tag: ['フォト', 'カメラ'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo_filter',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo_library',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo_size_select_actual',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo_size_select_large',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'photo_size_select_small',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'picture_as_pdf',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'portrait',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'remove_red_eye',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'rotate_90_degrees_ccw',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'rotate_left',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'rotate_right',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'slideshow',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'straighten',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'style',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'switch_camera',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'switch_video',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'tag_faces',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'texture',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'timelapse',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'timer',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'timer_10',
    tag: ['10', '秒'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'timer_3',
    tag: ['3', '秒'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'timer_off',
    tag: ['アラーム', '時計', 'タイマー', 'clock', 'timer', 'alarm'],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'tonality',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'transform',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'tune',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'view_comfy',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'view_compact',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'vignette',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'wb_auto',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'wb_cloudy',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'wb_incandescent',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'wb_iridescent',
    tag: [],
  },
  {
    name: 'material',
    genre: 'image',
    icon: 'wb_sunny',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'add_location',
    tag: ['＋', '+', 'add', '追加', '場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'beenhere',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions',
    tag: ['方向'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_bike',
    tag: ['自転車', 'bicycle'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_boat',
    tag: ['船'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_bus',
    tag: ['バス'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_car',
    tag: ['車'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_railway',
    tag: ['電車'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_run',
    tag: ['ランニング', '走'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_subway',
    tag: ['地下鉄', '電車'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_transit',
    tag: ['電車'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'directions_walk',
    tag: ['歩'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'edit_location',
    tag: ['ペン', 'edit', 'edit', '編集', '場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'ev_station',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'flight',
    tag: ['飛行機'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'hotel',
    tag: ['ホテル', 'bed', 'ベッド'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'layers',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'layers_clear',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_activity',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_airport',
    tag: ['飛行機'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_atm',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_bar',
    tag: ['バー'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_cafe',
    tag: ['カフェ'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_car_wash',
    tag: ['洗車'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_convenience_store',
    tag: ['コンビニ'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_dining',
    tag: ['ダイニング', 'ご飯', 'レストラン', 'Restaurant', '飲食'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_drink',
    tag: ['飲'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_florist',
    tag: ['花'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_gas_station',
    tag: ['ガソリン', 'スタンド'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_grocery_store',
    tag: ['ショッピング', 'カート', 'スーパー'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_hospital',
    tag: ['病院'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_hotel',
    tag: ['ホテル', 'bed', 'ベッド'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_laundry_service',
    tag: ['ランドリー', '洗濯'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_library',
    tag: ['ライブラリー', '図書館'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_mall',
    tag: ['ショッピング'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_movies',
    tag: ['映画', 'ムービー', 'film', '映画'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_offer',
    tag: ['その他', 'タグ', 'タグ'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_parking',
    tag: ['パーキング', '駐車'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_pharmacy',
    tag: ['薬局', 'ドラッグ'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_phone',
    tag: ['電話', '受話器'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_pizza',
    tag: ['ピザ'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_play',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_post_office',
    tag: ['mail', 'メール'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_printshop',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_see',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_shipping',
    tag: ['トラック'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'local_taxi',
    tag: ['タクシー'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'map',
    tag: ['マップ'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'my_location',
    tag: ['現在', '位置'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'navigation',
    tag: ['ナビ'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'near_me',
    tag: ['ナビ', 'navigation'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'person_pin',
    tag: ['場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin', '人', 'people', 'person'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'person_pin_circle',
    tag: ['場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin', '人', 'people', 'person'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'pin_drop',
    tag: ['場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'place',
    tag: ['場所', '現在位置', 'ロケーション', 'ピン', '地図', 'map', 'マップ', 'pin'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'rate_review',
    tag: ['レビュー'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'restaurant',
    tag: ['レストラン', '飲食'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'restaurant_menu',
    tag: ['レストラン', '飲食'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'satellite',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'store_mall_directory',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'streetview',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'subway',
    tag: ['鉄道'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'terrain',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'traffic',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'train',
    tag: ['電車'],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'tram',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'transfer_within_a_station',
    tag: [],
  },
  {
    name: 'material',
    genre: 'maps',
    icon: 'zoom_out_map',
    tag: ['ズームアウト'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'apps',
    tag: ['アプリ'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'arrow_back',
    tag: ['矢印', '←', '左', 'prev', 'previous', 'back', '戻る'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'arrow_downward',
    tag: ['矢印', '↓', '下', 'ダウンロード'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'arrow_drop_down',
    tag: ['矢印', '↓', '下'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'arrow_drop_down_circle',
    tag: ['矢印', '↓', '下'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'arrow_drop_up',
    tag: ['矢印', '↑', '上'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'arrow_forward',
    tag: ['矢印', '→', '右', 'go', 'next', '進む'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'arrow_upward',
    tag: ['矢印', '↑', '上'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'cancel',
    tag: ['cancel', 'キャンセル', '戻る', '×', 'バツ', '☓', 'back', 'バック', 'クリア', 'clear', 'クローズ', 'close'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'check',
    tag: ['チェック', 'レ点'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'chevron_left',
    tag: ['矢印', '←', '左'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'chevron_right',
    tag: ['矢印', '→', '右'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'close',
    tag: ['cancel', 'キャンセル', '戻る', '×', 'バツ', '☓', 'back', 'バック', 'クリア', 'clear', 'クローズ', 'close'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'expand_less',
    tag: ['矢印', '↑', '上'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'expand_more',
    tag: ['矢印', '↓', '下'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'first_page',
    tag: ['矢印', '←', '左'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'fullscreen',
    tag: [],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'fullscreen_exit',
    tag: [],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'last_page',
    tag: ['矢印', '→', '右'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'menu',
    tag: ['メニュー', 'menu', 'option', 'オプション'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'more_horiz',
    tag: ['メニュー', 'menu', 'option', 'オプション'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'more_vert',
    tag: ['メニュー', 'menu', 'option', 'オプション'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'refresh',
    tag: ['更新', 'update', '同期', 'sync'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'subdirectory_arrow_left',
    tag: ['矢印', '←', '左'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'subdirectory_arrow_right',
    tag: ['矢印', '→', '右'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'unfold_less',
    tag: ['矢印', '↑', '上', '↓', '下'],
  },
  {
    name: 'material',
    genre: 'navigation',
    icon: 'unfold_more',
    tag: ['矢印', '→', '右', '←', '左'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'adb',
    tag: ['android', 'developer', '開発者'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_flat',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_flat_angled',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_individual_suite',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_legroom_extra',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_legroom_normal',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_legroom_reduced',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_recline_extra',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'airline_seat_recline_normal',
    tag: ['座席', 'シート', '乗'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'bluetooth_audio',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'confirmation_number',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'disc_full',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'do_not_disturb',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'do_not_disturb_alt',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'do_not_disturb_off',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'do_not_disturb_on',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'drive_eta',
    tag: ['車', 'car'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'enhanced_encryption',
    tag: ['鍵', '施錠', 'ロック'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'event_available',
    tag: ['イベント'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'event_busy',
    tag: ['イベント'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'event_note',
    tag: ['イベント'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'folder_special',
    tag: ['フォルダー'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'live_tv',
    tag: ['TV', 'ライブ', 'テレビ'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'mms',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'more',
    tag: ['ネット', '回線', '電波'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'network_check',
    tag: ['ネット', '回線', '電波', 'ネットワーク'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'network_locked',
    tag: ['ネット', '回線', '電波', 'ネットワーク'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'no_encryption',
    tag: ['鍵', '施錠', 'ロック'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'ondemand_video',
    tag: ['ディスプレイ', 'デスクトップ', 'desktop', 'display', 'ビデオ'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'personal_video',
    tag: ['ディスプレイ', 'デスクトップ', 'desktop', 'display', 'ビデオ'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'phone_bluetooth_speaker',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'phone_forwarded',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'phone_in_talk',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'phone_locked',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'phone_missed',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'phone_paused',
    tag: ['携帯', '電話', '受話器', 'phone', 'フォン'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'power',
    tag: ['パワー', 'コンセント', 'Outlet', 'プラグ', 'plug'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'priority_high',
    tag: ['！', '!', '感嘆符', 'びっくり'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sd_card',
    tag: ['シム', 'メモリー', 'カード'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sim_card_alert',
    tag: ['シム', 'メモリー', 'カード'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sms',
    tag: ['メッセージ', 'message'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sms_failed',
    tag: ['メッセージ', 'message'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sync',
    tag: ['更新', 'update', '同期', 'sync'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sync_black',
    tag: ['更新', 'update', '同期', 'sync'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sync_disabled',
    tag: ['更新', 'update', '同期', 'sync'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'sync_problem',
    tag: ['更新', 'update', '同期', 'sync'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'system_update',
    tag: ['スマートフォン', 'smartphone', 'モバイル', 'mobile'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'tap_and_play',
    tag: ['スマートフォン', 'smartphone', 'モバイル', 'mobile'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'time_to_leave',
    tag: ['car', '車'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'vibration',
    tag: ['バイブ', 'ヴァイブ', 'ヴァイブレーション', 'ヴイブレーション'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'voice_chat',
    tag: ['ボイス', 'チャット'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'vpn_lock',
    tag: [],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'wc',
    tag: ['トイレ', 'restroom'],
  },
  {
    name: 'material',
    genre: 'notification',
    icon: 'wifi',
    tag: ['ネット', '回線', '電波', 'ネットワーク', 'network'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'ac_unit',
    tag: [],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'airport_shuttle',
    tag: ['バス', 'シャトル'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'all_inclusive',
    tag: [],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'beach_access',
    tag: [],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'business_center',
    tag: ['ビジネス', 'バック'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'casino',
    tag: [],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'child_care',
    tag: [],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'child_friendly',
    tag: ['ベビーカー'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'fitness_center',
    tag: ['フィットネス', 'ダンベル'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'free_breakfast',
    tag: ['カフェ', 'cafe', '飲', '朝食'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'golf_course',
    tag: ['ゴルフ'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'hot_tub',
    tag: ['風呂'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'kitchen',
    tag: ['キッチン', '冷蔵庫'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'pool',
    tag: ['プール', '水'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'room_service',
    tag: [],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'rv_hookup',
    tag: [],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'smoke_free',
    tag: ['スモーキング', 'タバコ', '煙草', 'たばこ', '禁煙'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'smoking_rooms',
    tag: ['スモーキング', 'タバコ', '煙草', 'たばこ', '禁煙'],
  },
  {
    name: 'material',
    genre: 'places',
    icon: 'spa',
    tag: [],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'cake',
    tag: ['ケーキ', '誕生日', 'birthday'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'domain',
    tag: ['ドメイン'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'group',
    tag: ['people', '人', '人間', 'グループ', 'person'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'group_add',
    tag: ['＋', '+', 'add', '追加', 'people', '人', '人間', 'グループ', 'person'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'location_city',
    tag: ['街', '町'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'mood',
    tag: ['顔', '絵文字', 'face'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'mood_bad',
    tag: ['顔', '絵文字', 'face'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'notifications',
    tag: ['通知', 'お知らせ', 'ベル', 'bell', '鐘'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'notifications_active',
    tag: ['通知', 'お知らせ', 'ベル', 'bell', '鐘'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'notifications_none',
    tag: ['通知', 'お知らせ', 'ベル', 'bell', '鐘'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'notifications_off',
    tag: ['通知', 'お知らせ', 'ベル', 'bell', '鐘'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'notifications_paused',
    tag: ['通知', 'お知らせ', 'ベル', 'bell', '鐘'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'pages',
    tag: [],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'party_mode',
    tag: [],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'people',
    tag: ['people', '人', '人間', '人', 'people', 'person', 'ユーザー', 'user', '誰'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'people_outline',
    tag: ['people', '人', '人間', '人', 'people', 'person', 'ユーザー', 'user', '誰'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'person',
    tag: ['people', '人', '人間', '人', 'people', 'person', 'ユーザー', 'user', '誰'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'person_add',
    tag: ['＋', '+', 'add', '追加', 'people', '人', '人間', '人', 'people', 'person', 'ユーザー', 'user', '誰'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'person_outline',
    tag: ['people', '人', '人間', '人', 'people', 'person', 'ユーザー', 'user', '誰'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'plus_one',
    tag: ['+', '1'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'poll',
    tag: ['投票', '世論', '調査'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'public',
    tag: ['地球', '公開'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'school',
    tag: ['学校', '学帽', '卒業'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'sentiment_dissatisfied',
    tag: ['顔', '絵文字', 'face'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'sentiment_neutral',
    tag: ['顔', '絵文字', 'face'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'sentiment_satisfied',
    tag: ['顔', '絵文字', 'face'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'sentiment_very_dissatisfied',
    tag: ['顔', '絵文字', 'face'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'sentiment_very_satisfied',
    tag: ['顔', '絵文字', 'face'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'share',
    tag: ['シェア', '共有'],
  },
  {
    name: 'material',
    genre: 'social',
    icon: 'whatshot',
    tag: ['売れ筋', '人気'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'check_box',
    tag: ['チェック', 'ボタン', 'レ点'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'check_box_outline_blank',
    tag: ['チェック', 'ボタン'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'indeterminate_check_box',
    tag: ['チェック', 'ボタン'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'radio_button_checked',
    tag: ['ラジオ', 'ボタン'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'radio_button_unchecked',
    tag: ['ラジオ', 'ボタン'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'star',
    tag: ['星'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'star_border',
    tag: ['星'],
  },
  {
    name: 'material',
    genre: 'toggle',
    icon: 'star_half',
    tag: ['星'],
  },
]
